// Generated by CoffeeScript 1.9.2
(function() {
  var prefixMatch;

  prefixMatch = new RegExp(/(?!xmlns)^.*:/);

  exports.normalize = function(str) {
    if (typeof str === 'string') {
      return str.toLowerCase();
    } else {
      return str;
    }
  };

  exports.firstCharLowerCase = function(str) {
    if (typeof str === 'string') {
      return str.charAt(0).toLowerCase() + str.slice(1);
    } else {
      return str;
    }
  };

  exports.stripPrefix = function(str) {
    return str.replace(prefixMatch, '');
  };

  exports.parseNumbers = function(str) {
    if (typeof str === 'string' && !isNaN(str)) {
      return str = str % 1 === 0 ? parseInt(str, 10) : parseFloat(str);
    } else {
      return str;
    }
  };

}).call(this);
